name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0,12 * * *" # Chạy 2 lần mỗi ngày (lúc 0h và 12h)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Bước 1: Checkout code repository
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Bước 2: Chạy Action Snake
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: LeatuyrBertyk # ĐỔI TÊN NGƯỜI DÙNG CỦA BẠN TẠI ĐÂY!
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
          # Tùy chỉnh (Tùy chọn)
          commits_on_top: false
          color_snake: orange

      # Bước 3: Đẩy file ảnh SVG/GIF đã tạo lên repo
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output # Tạo branch "output" riêng cho ảnh
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
